# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

skip_tags: true
branches:
  only:
  - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#
# Build worker image (VM template)
image: Visual Studio 2017

environment:
  VisualStudioVersion: 15.0
  TreatWarningsAsErrors: true
  CodeAnalysisTreatWarningsAsErrors: true

configuration: Release

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  msbuild src\jdt.sln /nologo /m /v:quiet /t:restore

build:
  project: src\jdt.sln  # path to Visual Studio solution or project
  verbosity: normal     # MSBuild verbosity level

#---------------------------------#
#       test configuration        #
#---------------------------------#

test:
  assemblies:
  - '**\*tests.dll'

#---------------------------------#
#     artifact configuration      #
#---------------------------------#

artifacts:
- path: bin\**\*.nupkg
  name: Nuget Package
